# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playlists_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(408, 429)
        Form.setStyleSheet("background: rgb(40, 40, 40)")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.open_playlist_btn = QtWidgets.QPushButton(Form)
        self.open_playlist_btn.setStyleSheet("color: white\n"
"")
        self.open_playlist_btn.setObjectName("open_playlist_btn")
        self.gridLayout.addWidget(self.open_playlist_btn, 4, 1, 1, 1)
        self.update_btn = QtWidgets.QToolButton(Form)
        self.update_btn.setStyleSheet("color:white")
        self.update_btn.setObjectName("update_btn")
        self.gridLayout.addWidget(self.update_btn, 0, 0, 1, 1)
        self.del_playlist_btn = QtWidgets.QPushButton(Form)
        self.del_playlist_btn.setStyleSheet("color: white")
        self.del_playlist_btn.setObjectName("del_playlist_btn")
        self.gridLayout.addWidget(self.del_playlist_btn, 4, 0, 1, 1)
        self.files_add_btn = QtWidgets.QPushButton(Form)
        self.files_add_btn.setStyleSheet("color: white;")
        self.files_add_btn.setObjectName("files_add_btn")
        self.gridLayout.addWidget(self.files_add_btn, 4, 2, 1, 1)
        self.your_playlists = QtWidgets.QListWidget(Form)
        self.your_playlists.setStyleSheet("color: white\n"
"")
        self.your_playlists.setObjectName("your_playlists")
        self.gridLayout.addWidget(self.your_playlists, 1, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Плейлисты"))
        self.open_playlist_btn.setText(_translate("Form", "Открыть плейлист"))
        self.update_btn.setText(_translate("Form", "Обновить плейлисты"))
        self.del_playlist_btn.setText(_translate("Form", "Удалить плейлист"))
        self.files_add_btn.setText(_translate("Form", "Добавить треки в плейлист"))
