# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 545)
        MainWindow.setMinimumSize(QtCore.QSize(805, 545))
        MainWindow.setStyleSheet("background: rgb(40, 40, 40)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plus_btn = QtWidgets.QToolButton(self.centralwidget)
        self.plus_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plus_btn.setStyleSheet("QToolButton{\n"
"    image: url(images/plus_btn.png);\n"
"    icon-size: 24px;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    image: url(images/plus_btn_pressed.png);\n"
"}")
        self.plus_btn.setText("")
        self.plus_btn.setObjectName("plus_btn")
        self.gridLayout.addWidget(self.plus_btn, 2, 2, 1, 1)
        self.playlistview = QtWidgets.QTableView(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.playlistview.setFont(font)
        self.playlistview.setStyleSheet("QTableView {\n"
"    selection-background-color: rgb(255, 157, 87);\n"
"    color: white;\n"
"}")
        self.playlistview.setObjectName("playlistview")
        self.gridLayout.addWidget(self.playlistview, 3, 2, 1, 2)
        self.current_track_lbl = QtWidgets.QLabel(self.centralwidget)
        self.current_track_lbl.setMaximumSize(QtCore.QSize(201, 83))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.current_track_lbl.setFont(font)
        self.current_track_lbl.setStyleSheet("color: white;")
        self.current_track_lbl.setObjectName("current_track_lbl")
        self.gridLayout.addWidget(self.current_track_lbl, 4, 0, 1, 1)
        self.add_text_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_text_btn.setStyleSheet("color:white;\n"
"")
        self.add_text_btn.setObjectName("add_text_btn")
        self.gridLayout.addWidget(self.add_text_btn, 2, 4, 1, 1)
        self.playlist_open_btn = QtWidgets.QPushButton(self.centralwidget)
        self.playlist_open_btn.setStyleSheet("color: white;")
        self.playlist_open_btn.setObjectName("playlist_open_btn")
        self.gridLayout.addWidget(self.playlist_open_btn, 2, 3, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("Slider {\n"
"    from: 1\n"
"    value: 25\n"
"    to: 100\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mix_btn = QtWidgets.QToolButton(self.widget)
        self.mix_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mix_btn.setStyleSheet("QToolButton{\n"
"    image: url(images/Mix_btn.png);\n"
"    icon-size: 28px;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    image: url(images/Mix_btn_pressed.png);\n"
"}")
        self.mix_btn.setText("")
        self.mix_btn.setObjectName("mix_btn")
        self.horizontalLayout.addWidget(self.mix_btn)
        self.back_btn = QtWidgets.QToolButton(self.widget)
        self.back_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn.setStyleSheet("QToolButton{\n"
"    image: url(images/back_btn.png);\n"
"    icon-size: 18px;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    image: url(images/back_btn_pressed.png);\n"
"}")
        self.back_btn.setText("")
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)
        self.play_btn = QtWidgets.QToolButton(self.widget)
        self.play_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play_btn.setStyleSheet("QToolButton{\n"
"    image: url(images/play_btn.png);\n"
"    icon-size: 30px;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    image: url(images/play_pressed_btn.png);\n"
"}")
        self.play_btn.setText("")
        self.play_btn.setObjectName("play_btn")
        self.horizontalLayout.addWidget(self.play_btn)
        self.pause_btn = QtWidgets.QToolButton(self.widget)
        self.pause_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pause_btn.setStyleSheet("QToolButton{\n"
"    image: url(images/pause_btn.png);\n"
"    icon-size: 20px;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    image: url(images/pause_btn_pressed.png);\n"
"}")
        self.pause_btn.setText("")
        self.pause_btn.setObjectName("pause_btn")
        self.horizontalLayout.addWidget(self.pause_btn)
        self.next_btn = QtWidgets.QToolButton(self.widget)
        self.next_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_btn.setStyleSheet("QToolButton{\n"
"    image: url(images/previous_btn.png);\n"
"    icon-size: 18px;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    image: url(images/previous_btn_pressed.png);\n"
"}")
        self.next_btn.setText("")
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout.addWidget(self.next_btn)
        self.repeat_btn = QtWidgets.QToolButton(self.widget)
        self.repeat_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.repeat_btn.setStyleSheet("QToolButton{\n"
"    image: url(images/repeat_btn.png);\n"
"    icon-size: 28px;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    image: url(images/repeat_btn_pressed.png);\n"
"}")
        self.repeat_btn.setText("")
        self.repeat_btn.setObjectName("repeat_btn")
        self.horizontalLayout.addWidget(self.repeat_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.duration_now_lbl = QtWidgets.QLabel(self.widget)
        self.duration_now_lbl.setStyleSheet("color: white;")
        self.duration_now_lbl.setText("")
        self.duration_now_lbl.setObjectName("duration_now_lbl")
        self.horizontalLayout_2.addWidget(self.duration_now_lbl)
        self.rewind_slider = QtWidgets.QSlider(self.widget)
        self.rewind_slider.setStyleSheet("QSlider::groove:horizontal { \n"
"    background-color: rgb(66, 66, 66);\n"
"    border: 1px solid black; \n"
"    height: 5px; \n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal { \n"
"    background-color: orange; \n"
"    border: 1px solid orange; \n"
"    width: 10px; \n"
"    height: 10px; \n"
"    line-height: 10px; \n"
"    margin-top: -5px; \n"
"    margin-bottom: -5px; \n"
"    border-radius: 5px; \n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover { \n"
"    background-color: rgb(255, 248, 53)\n"
"}")
        self.rewind_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rewind_slider.setObjectName("rewind_slider")
        self.horizontalLayout_2.addWidget(self.rewind_slider)
        self.duration_lbl = QtWidgets.QLabel(self.widget)
        self.duration_lbl.setStyleSheet("color: white;")
        self.duration_lbl.setText("")
        self.duration_lbl.setObjectName("duration_lbl")
        self.horizontalLayout_2.addWidget(self.duration_lbl)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.off_sound_btn = QtWidgets.QToolButton(self.widget)
        self.off_sound_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.off_sound_btn.setStyleSheet("QToolButton{\n"
"    image: url(images/wsound_btn.png);\n"
"    icon-size: 18px;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    image: url(images/wsound_btn_pressed.png);\n"
"}")
        self.off_sound_btn.setText("")
        self.off_sound_btn.setObjectName("off_sound_btn")
        self.horizontalLayout_3.addWidget(self.off_sound_btn)
        self.volume_slider = QtWidgets.QSlider(self.widget)
        self.volume_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.horizontalLayout_3.addWidget(self.volume_slider)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 4, 2, 1, 2)
        self.image_lbl = QtWidgets.QLabel(self.centralwidget)
        self.image_lbl.setMaximumSize(QtCore.QSize(201, 16777215))
        self.image_lbl.setText("")
        self.image_lbl.setObjectName("image_lbl")
        self.gridLayout.addWidget(self.image_lbl, 3, 0, 1, 1)
        self.text_view = QtWidgets.QTextEdit(self.centralwidget)
        self.text_view.setMaximumSize(QtCore.QSize(229, 16777215))
        self.text_view.setStyleSheet("color: white")
        self.text_view.setObjectName("text_view")
        self.gridLayout.addWidget(self.text_view, 3, 4, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 805, 18))
        self.menuBar.setStyleSheet("QMenuBar {\n"
"    spacing: 3px; /* spacing between menu bar items */\n"
"    color: white;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 1px 4px;\n"
"    background: transparent;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"}\n"
"")
        self.menuBar.setObjectName("menuBar")
        self.menuMP3_Player = QtWidgets.QMenu(self.menuBar)
        self.menuMP3_Player.setObjectName("menuMP3_Player")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.file_act = QtWidgets.QAction(MainWindow)
        self.file_act.setObjectName("file_act")
        self.folder_act = QtWidgets.QAction(MainWindow)
        self.folder_act.setObjectName("folder_act")
        self.menuMP3_Player.addAction(self.file_act)
        self.menuMP3_Player.addAction(self.folder_act)
        self.menuBar.addAction(self.menuMP3_Player.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Audio Player"))
        self.plus_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Создать плейлист</p></body></html>"))
        self.plus_btn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Создать плейлист</p></body></html>"))
        self.current_track_lbl.setText(_translate("MainWindow", "Выберите музыку"))
        self.add_text_btn.setText(_translate("MainWindow", "Добавить текст"))
        self.playlist_open_btn.setText(_translate("MainWindow", "Открыть плейлисты"))
        self.menuMP3_Player.setTitle(_translate("MainWindow", "OpenFiles"))
        self.action.setText(_translate("MainWindow", "Поддержка"))
        self.action_5.setText(_translate("MainWindow", "Создать плейлист"))
        self.action_6.setText(_translate("MainWindow", "Удалить плейлист"))
        self.file_act.setText(_translate("MainWindow", "Открыть файлы"))
        self.folder_act.setText(_translate("MainWindow", "Открыть папку"))
