# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text_writer_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(438, 431)
        Form.setStyleSheet("background: rgb(40, 40, 40)")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.update_txt_btn = QtWidgets.QPushButton(Form)
        self.update_txt_btn.setStyleSheet("color: white")
        self.update_txt_btn.setObjectName("update_txt_btn")
        self.gridLayout.addWidget(self.update_txt_btn, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setStyleSheet("color: white\n"
"")
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 2, 0, 1, 2)
        self.writer_line = QtWidgets.QPlainTextEdit(Form)
        self.writer_line.setStyleSheet("color: white")
        self.writer_line.setReadOnly(False)
        self.writer_line.setObjectName("writer_line")
        self.gridLayout.addWidget(self.writer_line, 1, 0, 1, 3)
        self.songs_box = QtWidgets.QComboBox(Form)
        self.songs_box.setStyleSheet("color: white")
        self.songs_box.setObjectName("songs_box")
        self.gridLayout.addWidget(self.songs_box, 0, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Введите текст"))
        self.update_txt_btn.setText(_translate("Form", "Изменить текст"))
        self.label.setText(_translate("Form", "Выберите песню:"))
        self.save_btn.setText(_translate("Form", "Сохранить"))
